apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: macklin-volume
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce #ReadWriteMany (only CephFS vs RBD)
  resources:
    requests:
      storage: 1Ti
